'use strict';

const defaultConfig = {
	rules: {
		'bin-type': 'error',
		'bundledDependencies-type': 'error',
		'config-type': 'error',
		'cpu-type': 'error',
		'dependencies-type': 'error',
		'description-type': 'error',
		'devDependencies-type': 'error',
		'directories-type': 'error',
		'engines-type': 'error',
		'files-type': 'error',
		'homepage-type': 'error',
		'keywords-type': 'error',
		'license-type': 'error',
		'main-type': 'error',
		'man-type': 'error',
		'name-format': 'error',
		'name-type': 'error',
		'optionalDependencies-type': 'error',
		'os-type': 'error',
		'peerDependencies-type': 'error',
		'prefer-alphabetical-bundledDependencies': 'error',
		'prefer-alphabetical-dependencies': 'error',
		'prefer-alphabetical-devDependencies': 'error',
		'prefer-alphabetical-optionalDependencies': 'error',
		'prefer-alphabetical-peerDependencies': 'error',
		'prefer-property-order': [
			'error',
			[
				'name',
				'version',
				'description',
				'author',
				'license',
				'keywords',
				'homepage',
				'repository',
				'bugs',
				'engines',
				'directories',
				'files',
				'main',
				'module',
				'bin',
				'dependencies',
				'devDependencies',
				'peerDependencies',
				'publishConfig',
				'scripts',
			],
		],
		'preferGlobal-type': 'error',
		'private-type': 'error',
		'repository-type': 'error',
		'require-author': 'error',
		'require-bugs': 'error',
		'require-description': 'error',
		'require-engines': 'off',
		'require-homepage': 'error',
		'require-keywords': 'error',
		'require-license': 'error',
		'require-name': 'error',
		'require-repository': 'error',
		'require-version': 'error',
		'scripts-type': 'error',
		'valid-values-license': [ 'error', [
			'GPL-2.0-or-later',
		] ],
		'version-format': 'error',
		'version-type': 'error',
	},
};

module.exports = defaultConfig;
